workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release --target=main.dart
    artifacts:
      - build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - qdhuy2000gl@gmail.com
